apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/AgriSenseNet/ArgoCD.git
    path: manifests/services
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true