apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: disabled