apiVersion: v1
kind: Namespace
metadata:
  name: agri-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-backend
  namespace: agri-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-backend
  template:
    metadata:
      labels:
        app: agri-backend
    spec:
      containers:
        - name: agri-backend
          image: ghcr.io/agrisensenet/agri-backend@sha256:e89b60f4892fabf72f28b04b1672c4d3ec0894c48a6a5d1e42e83229a01bbb33
          ports:
            - name: http
              containerPort: 3001
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: agri-backend
  namespace: agri-backend
  labels:
    app.kubernetes.io/name: agri-backend
spec:
  selector:
    app: agri-backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
