apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - influxdb
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb2
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
