apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: postgres
  namespace: postgres
spec:
  hosts:
  - postgres.cropwise.garden
  gateways:
  - istio-ingress/istio-gateway
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: postgres-postgresql.postgres.svc.cluster.local
        port:
          number: 5432

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: influxdb
  namespace: influxdb
spec:
  hosts:
  - influxdb.cropwise.garden
  gateways:
  - istio-ingress/istio-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: influxdb-influxdb2.influxdb.svc.cluster.local
        port:
          number: 8086

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: airflow
  namespace: airflow
spec:
  hosts:
  - airflow.cropwise.garden
  gateways:
  - istio-ingress/istio-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: airflow-webserver.airflow.svc.cluster.local
        port:
          number: 8080

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vault
  namespace: vault
spec:
  hosts:
  - vault.cropwise.garden
  gateways:
  - istio-ingress/istio-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: vault.vault.svc.cluster.local
        port:
          number: 8200