apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: "1.13.0"
    helm:
      values: |
        executor: LocalExecutor
        airflowVersion: "2.9.0"
        defaultAirflowTag: "2.9.0"
        images:
          airflow:
            repository: apache/airflow
            tag: "2.9.0"
        webserver:
          service:
            type: ClusterIP
        scheduler:
          replicas: 1
        triggerer:
          enabled: false
        migrateDatabaseJob:
          useHelmHooks: false
        createUserJob:
          useHelmHooks: false
        postgresql:
          enabled: false
        data:
          metadataConnection:
            user: postgres
            pass: test
            host: postgres-postgresql.postgres
            port: 5432
            db: airflow
            protocol: postgresql
            sslmode: disable
        redis:
          enabled: false
        persistence:
          enabled: true
          storageClass: standard-gp3
          size: 2Gi
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        webserverSecretKey: "my-webserver-secret-key"
        fernetKey: "my-fernet-key"
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true