apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agri-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/AgriSenseNet/ArgoCD.git
    path: manifests/agri-backend
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: agri-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
